### ISSUE TITLE
app! is broken

### ISSUE THREAD

**Issue by et1975** [japaric/cortex-m-rtfm#82]
on my nightly I get:

>cargo  build --target thumbv7em-none-eabihf --examples
>   Compiling cortex-m-rtfm v0.3.2 (file:///Users/eugene.tolmachev/sources/cortex-m-rtfm)
>error[E0658]: procedural macros cannot expand to modules (see issue #38356)
>  --> examples/safe-static-mut-ref.rs:12:1
>   |
>12 | / app! {
>13 | |     device: stm32f103xx,
>14 | |
>15 | |     resources: {
>...  |
>21 | |     },
>22 | | }
>   | |_^
>   |
>   = help: add #![feature(proc_macro_gen)] to the crate attributes to enable

Anyone knows which toolchain/dependencies combo does work?

**Comment by TeXitoi** [comment]
I have a working RTFM program with nightly-2018-07-10 based on your repo, but I had to tweak it a bit:
  https://github.com/TeXitoi/cortex-m-rtfm/commit/22b2084dc7eb9b7681465ada59b12094f4f9af59

I also need to downgrad failure and proc-macro with:
```
cargo update --package failure --precise 0.1.1
cargo update --package failure_derive --precise 0.1.1
cargo update --package proc-macro2 --precise 0.4.7
```

The working repo: https://github.com/TeXitoi/wave-test

The problem you have seen is related to the changing name of the features related to proc_macro. Something like that is required to make it working:
  https://github.com/japaric/rtfm-syntax/pull/9

**Comment by japaric** [comment]
v0.4.0-beta.1 works with 1.31-beta and the latest versions of the cortex-m crates.
