### ISSUE TITLE
cortex-m-rtfm-macros does not build on latest nightly 1.38

### ISSUE THREAD

**Issue by korken89** [japaric/cortex-m-rtfm#213]
The following error is produced, seems to be a simple import change though:

```
   Compiling cortex-m-rtfm-macros v0.4.3

error[E0433]: failed to resolve: unresolved import
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/owned-singleton-macros-0.1.0/src/lib.rs:120:46
    |
120 |         let punctuated = Punctuated::<Ident, Token![,]>::parse_terminated(input)?;
    |                                              ^^^^^^^^^
    |                                              |
    |                                              unresolved import
    |                                              help: a similar path exists: `syn::token`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

   Compiling nrf52832-pac v0.8.0
error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: Could not compile `owned-singleton-macros`.
warning: build failed, waiting for other jobs to finish...
error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
  --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:32:28
   |
32 |             let _eq_token: Token![=] = input.parse()?;
   |                            ^^^^^^^^^ maybe a missing `extern crate token;`?
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
  --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:59:20
   |
59 |             let _: Token![,] = input.parse()?;
   |                    ^^^^^^^^^ maybe a missing `extern crate token;`?
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
  --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:72:19
   |
72 |     _const_token: Token![const],
   |                   ^^^^^^^^^^^^^ maybe a missing `extern crate token;`?
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
  --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:74:19
   |
74 |     _colon_token: Token![:],
   |                   ^^^^^^^^^ maybe a missing `extern crate token;`?
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
  --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:76:16
   |
76 |     _eq_token: Token![=],
   |                ^^^^^^^^^ maybe a missing `extern crate token;`?
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
  --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:79:18
   |
79 |     _semi_token: Token![;],
   |                  ^^^^^^^^^ maybe a missing `extern crate token;`?
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:438:26
    |
438 |     pub unsafety: Option<Token![unsafe]>,
    |                          ^^^^^^^^^^^^^^ maybe a missing `extern crate token;`?
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:513:20
    |
513 |             let _: Token![=] = content.parse()?;
    |                    ^^^^^^^^^ maybe a missing `extern crate token;`?
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:537:53
    |
537 |             for ident in inner.call(Punctuated::<_, Token![,]>::parse_terminated)? {
    |                                                     ^^^^^^^^^ maybe a missing `extern crate token;`?
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:588:20
    |
588 |             let _: Token![,] = content.parse()?;
    |                    ^^^^^^^^^ maybe a missing `extern crate token;`?
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:609:26
    |
609 |     pub unsafety: Option<Token![unsafe]>,
    |                          ^^^^^^^^^^^^^^ maybe a missing `extern crate token;`?
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:728:26
    |
728 |     pub unsafety: Option<Token![unsafe]>,
    |                          ^^^^^^^^^^^^^^ maybe a missing `extern crate token;`?
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:826:26
    |
826 |     pub unsafety: Option<Token![unsafe]>,
    |                          ^^^^^^^^^^^^^^ maybe a missing `extern crate token;`?
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:880:28
    |
880 |     pub mutability: Option<Token![mut]>,
    |                            ^^^^^^^^^^^ maybe a missing `extern crate token;`?
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:978:16
    |
978 |         let _: Token![=] = content.parse()?;
    |                ^^^^^^^^^ maybe a missing `extern crate token;`?
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
    --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:1063:57
     |
1063 |                 for ident in inner.call(Punctuated::<_, Token![,]>::parse_terminated)? {
     |                                                         ^^^^^^^^^ maybe a missing `extern crate token;`?
     |
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
    --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:1125:16
     |
1125 |         let _: Token![,] = content.parse()?;
     |                ^^^^^^^^^ maybe a missing `extern crate token;`?
     |
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
    --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtfm-macros-0.4.3/src/syntax.rs:1180:26
     |
1180 |     pub unsafety: Option<Token![unsafe]>,
     |                          ^^^^^^^^^^^^^^ maybe a missing `extern crate token;`?
     |
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/internals/ast.rs:142:44
    |
142 |     variants: &'a Punctuated<syn::Variant, Token![,]>,
    |                                            ^^^^^^^^^
    |                                            |
    |                                            unresolved import
    |                                            help: a similar path exists: `syn::token`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/internals/ast.rs:187:40
    |
187 |     fields: &'a Punctuated<syn::Field, Token![,]>,
    |                                        ^^^^^^^^^
    |                                        |
    |                                        unresolved import
    |                                        help: a similar path exists: `syn::token`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
    --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/internals/attr.rs:1542:44
     |
1542 |     metas: &'a Punctuated<syn::NestedMeta, Token![,]>,
     |                                            ^^^^^^^^^
     |                                            |
     |                                            unresolved import
     |                                            help: a similar path exists: `syn::token`
     |
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
    --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/internals/attr.rs:1586:44
     |
1586 |     items: &'a Punctuated<syn::NestedMeta, Token![,]>,
     |                                            ^^^^^^^^^
     |                                            |
     |                                            unresolved import
     |                                            help: a similar path exists: `syn::token`
     |
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
    --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/internals/attr.rs:1594:44
     |
1594 |     items: &'a Punctuated<syn::NestedMeta, Token![,]>,
     |                                            ^^^^^^^^^
     |                                            |
     |                                            unresolved import
     |                                            help: a similar path exists: `syn::token`
     |
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
    --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/internals/attr.rs:1602:41
     |
1602 |     items: &Punctuated<syn::NestedMeta, Token![,]>,
     |                                         ^^^^^^^^^
     |                                         |
     |                                         unresolved import
     |                                         help: a similar path exists: `syn::token`
     |
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
    --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/internals/attr.rs:1702:56
     |
1702 |     struct BorrowedLifetimes(Punctuated<syn::Lifetime, Token![+]>);
     |                                                        ^^^^^^^^^
     |                                                        |
     |                                                        unresolved import
     |                                                        help: a similar path exists: `syn::token`
     |
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/bound.rs:198:31
    |
198 |                 colon_token: <Token![:]>::default(),
    |                               ^^^^^^^^^
    |                               |
    |                               unresolved import
    |                               help: a similar path exists: `syn::token`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/bound.rs:232:27
    |
232 |             colon_token: <Token![:]>::default(),
    |                           ^^^^^^^^^
    |                           |
    |                           unresolved import
    |                           help: a similar path exists: `syn::token`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/bound.rs:289:36
    |
289 |                         lt_token: <Token![<]>::default(),
    |                                    ^^^^^^^^^
    |                                    |
    |                                    unresolved import
    |                                    help: a similar path exists: `syn::token`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
   --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/bound.rs:309:36
    |
309 |                         gt_token: <Token![>]>::default(),
    |                                    ^^^^^^^^^
    |                                    |
    |                                    unresolved import
    |                                    help: a similar path exists: `syn::token`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> /home/emifre/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/fragment.rs:58:18
   |
58 |                 <Token![,]>::default().to_tokens(out);
   |                  ^^^^^^^^^
   |                  |
   |                  unresolved import
   |                  help: a similar path exists: `syn::token`
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 18 previous errors

For more information about this error, try `rustc --explain E0433`.
error: Could not compile `cortex-m-rtfm-macros`.
```

**Comment by jonas-schievink** [comment]
See https://github.com/rust-lang/rust/issues/62562

**Comment by korken89** [comment]
Thanks for finding the root cause!
